import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./themes/globals.css"
import { ConfigProvider } from "antd";
import theme from "./themes/theme.config";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tech-Quest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ConfigProvider theme={theme}>
      <body className={inter.className}>{children}</body>
      </ConfigProvider>
    </html>
  );
}
