import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./themes/globals.css"
import { ConfigProvider } from "antd";
import theme from "./themes/theme.config";
import ClientLayout from './Components/ClientLayout/page';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Tech-Quest",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConfigProvider theme={theme}>
              <ClientLayout>
              {children}
            </ClientLayout>
        </ConfigProvider>
      </body>
    </html>
  );
}
